/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * High-performance OrderBook implementation with lock-free operations
 */
export class JsOrderBook {
  /**
   * Create a new OrderBook for the specified symbol
   * @param symbol - Trading symbol (e.g., "BTCUSD")
   */
  constructor(symbol: string)
  
  /**
   * Add a limit order to the order book
   * @param price - Order price in smallest unit (e.g., cents)
   * @param quantity - Order quantity
   * @param side - Order side ("Buy" or "Sell")
   * @param timeInForce - Time in force ("GTC", "IOC", or "FOK")
   * @returns Order ID (UUID string)
   * @throws Error if parameters are invalid or order cannot be placed
   */
  addLimitOrder(price: number, quantity: number, side: string, timeInForce: string): string
  
  /**
   * Get the best bid price
   * @returns Best bid price or null if no bids exist
   */
  bestBid(): number | null
  
  /**
   * Get the best ask price
   * @returns Best ask price or null if no asks exist
   */
  bestAsk(): number | null
}

/**
 * Order sides
 */
export type OrderSide = "Buy" | "Sell"

/**
 * Time in force values
 */
export type TimeInForce = "GTC" | "IOC" | "FOK"

/**
 * Order book configuration
 */
export interface OrderBookConfig {
  /** Trading symbol */
  symbol: string
}

/**
 * Order details
 */
export interface OrderDetails {
  /** Order ID */
  id: string
  /** Order price */
  price: number
  /** Order quantity */
  quantity: number
  /** Order side */
  side: OrderSide
  /** Time in force */
  timeInForce: TimeInForce
}

/**
 * Price level information
 */
export interface PriceLevel {
  /** Price level */
  price: number
  /** Total quantity at this price */
  quantity: number
  /** Number of orders at this price */
  orderCount: number
}